### ISSUE TITLE
install ESMF820bs14 for ufs-weather across platforms

### ISSUE THREAD

**Issue by DeniseWorthen** [NOAA-EMC/hpc-stack#281] opened 2021-07-26 17:59 UTC
**Is your feature request related to a problem? Please describe.**

ufs-weather-model needs to update to esmf_8.2.0 BS 14. This release has been tested on Hera.intel and all regression tests pass (98dfa96)

**Describe the solution you'd like**

Install esmf 8.2.0 bs 14 within hpc-stack v1.1.0 on gaea,hera,jet,orion and dell-p3 and cray.

**Additional context**

**Comment by edwardhartnett** [comment] 2021-07-26 19:45
We have discussed this in the past and determined that we should only be updating ESMF to full releases. In other words, not to beta-releases.

If you need an update of ESMF we should ask them to do a full release so it can be properly installed on our systems.

**Comment by arunchawla-NOAA** [comment] 2021-07-28 13:09
@edwardhartnett I understand why we want to install full releases and the ESMF team has updates its release policy to do more than one release per year. But we will need some beta snapshots installed to do detailed testing with the full model on multiple platforms as ESMF touches multiple parts of the UFS. We need this beta snapshot for the coupled UFS model. Basic level tests have already been done with the UFS model by @mark-a-potts on HERA

**Comment by edwardhartnett** [comment] 2021-07-28 13:26
OK, if we must, we must.

I believe the problem is that we have no good way of distinguishing beta releases in our FindESMF.cmake code. So we cannot build into the build system the checking to ensure that we have the version we need.

**Comment by kgerheiser** [comment] 2021-08-02 13:31
I have installed it on Orion and Jet.

**Comment by edwardhartnett** [comment] 2021-08-02 14:11
@kgerheiser this beta version will be part of the 1.2.0 hpc-stack release, right?

**Comment by kgerheiser** [comment] 2021-08-02 14:12
Yes

**Comment by climbfuji** [comment] 2021-08-02 14:24
@edwardhartnett @kgerheiser I realized that the Cheyenne config files need to be updated before the 1.2.0 release. A tiny PR, will create in a few minutes. The new compiler versions for Intel and GNU are already used by the ufs-weather-model, but we didn't update hpc-stack yet.

**Comment by climbfuji** [comment] 2021-08-02 15:59
I didn't realize that ESMF 8.2.0 bs14 only goes into v1.2.0, so I installed it in v1.1.0 on Gaea (Intel) and Cheyenne (both Intel and GNU). Doesn't hurt.

**Comment by kgerheiser** [comment] 2021-08-02 16:00
That's fine. That's what I did too.

**Comment by arunchawla-NOAA** [comment] 2021-08-13 14:16
Is this already done ?

**Comment by kgerheiser** [comment] 2021-08-13 14:21
It's done on Orion, Jet, Gaea, and Cheyenne.

@Hang-Lei-NOAA Hera and WCOSS?

**Comment by climbfuji** [comment] 2021-08-13 14:34
We just discussed this in the code manager meeting. We will need the new ESMF version as part of the hpc-stack v1.2.0 roll-out (no longer needed in v1.1.0). This should also include a new (yet to be created) tag of FMS 2021.03. The FMS tag will be created next week.

We are hoping to have hpc-stack v1.2.0 with ESMF 8.2.0 bs14 and FMS 2021.03 available on all platforms by the end of next week. @kgerheiser is that realistic between the two of us?

**Comment by kgerheiser** [comment] 2021-08-13 14:37
Sure, that works for me.

**Comment by Hang-Lei-NOAA** [comment] 2021-08-13 14:39
I am updating dell and Hera

**Comment by edwardhartnett** [comment] 2021-08-16 12:32
I believe this has been done. Can we close this ticket?

**Comment by climbfuji** [comment] 2021-08-16 12:54
Not exactly. As described in a previous comment here (https://github.com/NOAA-EMC/hpc-stack/issues/281#issuecomment-898500998), we need to update hpc-stack v1.2.0 before it gets rolled out the first time (or as a follow-up after installing the default versions in v1.2.0, please advise) to include:
- FMS 2021.03 (tag will be created this week)
- ESMF 8.2.0 bs14

While ESMF 8.2.0 bs14 has been installed on most platforms in v1.1.0, it has not been used - the update to using 8.2.0 bs14 is going to happen when we roll out v1.2.0 this week (so that the ufs-weather-model can be updated beginning of next week).

Once we hear from GFDL that FMS 2021.03 was created, we can start with rolling out the release.

**Comment by kgerheiser** [comment] 2021-09-09 21:08
This is done

**Closed as completed by kgerheiser** 2021-09-09 21:08 UTC
Labels: enhancement
