### ISSUE TITLE
set up cron job on hpc systems

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/hpc-stack#81] opened 2020-11-18 20:59 UTC
cron jobs can test hpc-stack and email the results.

**Comment by edwardhartnett** [comment] 2020-11-21 13:50
Should be set up on: Orion, Hera, Jet, WCOSS-Dell, cheyenne, gaea.

**Comment by edwardhartnett** [comment] 2020-12-10 16:19
@aerorahul @kgerheiser this will be a topic in the meeting today and the top priority item for the next release. We need to get a daily build on all our required platforms.

**Comment by kgerheiser** [comment] 2020-12-10 16:31
I started working on this and have a basic script. However, NOAA systems have firewalls that block certain connections (gitlab, wget, etc). Not everything can be downloaded locally. For that we use DOWNLOAD_ONLY option and then upload it to the system to built it. 

I think there are only a few things that don't use Github (which isn't blocked) so the script needs to be disable those things that are for this to work.

**Comment by kgerheiser** [comment] 2020-12-17 21:22
I have it running on Hera, Jet, Orion, and WCOSS Dell.

I can have the build part run on Gaea, but I can't run regression tests on there.

**Comment by climbfuji** [comment] 2020-12-17 21:27
> I have it running on Hera, Jet, Orion, and WCOSS Dell.
> 
> I can have the build part run on Gaea, but I can't run regression tests on there.

I can help. Maybe still before my vacation Dec 21-25, otherwise afterwards.

**Comment by kgerheiser** [comment] 2020-12-17 21:44
Might be after.

I have a few changes to make now that I've been running it for a few days.

**Comment by edwardhartnett** [comment] 2021-03-01 18:29
Is this running well now?

Is there a daily email output? If so, can you add my email address?

**Comment by kgerheiser** [comment] 2021-03-01 19:32
Yes, I will do that.

**Comment by aerorahul** [comment] 2021-07-08 15:36
@kgerheiser @edwardhartnett 
What do we need to do to close this issue?

**Comment by kgerheiser** [comment] 2021-07-08 15:37
can be closed

**Comment by climbfuji** [comment] 2021-07-12 02:51
This has not been done on all systems if I remember correctly. What about gaea? cheyenne?

What does "hpc systems" refer to? tier-1 platforms for the ufs-weather-model? If so, then gaea and cheyenne must be included.

**Comment by edwardhartnett** [comment] 2021-07-12 07:37
Who can do this on gaea and cheyenne? @kgerheiser does not have permissions.

Also, are these cron tasks sending emails when they succeed/fail? If so, I am not getting them...

**Comment by climbfuji** [comment] 2021-07-12 14:47
> Who can do this on gaea and cheyenne? @kgerheiser does not have permissions.
> 
> Also, are these cron tasks sending emails when they succeed/fail? If so, I am not getting them...

I can do both, but we agreed in the past that EMC should take over responsibility on gaea (starting from hpc-stack v1.2.0). I thought that @kgerheiser has access nowadays.

**Comment by kgerheiser** [comment] 2021-07-12 14:51
I can takeover Gaea, and I do have access. Though I don't think I have compute capability.

**Comment by climbfuji** [comment] 2021-07-12 15:09
> I can takeover Gaea, and I do have access. Though I don't think I have compute capability.

If compute is needed and you don't have, please let me know and I will set it up instead. I would need instructions for the cron jobs for Cheyenne, too. Thanks ...

**Comment by edwardhartnett** [comment] 2021-07-12 16:22
I don't think I am getting an emails for success or failure. Can you add me to the list of people who get emailed when this runs?

**Comment by edwardhartnett** [comment] 2021-07-27 13:36
@kgerheiser what machines is this cron job working on?

Can you add me to the email list so I can see the results?

What machines do we still want to set up cron jobs on? Can we bump the remaining machines to after the 1.2.0 release of hpc-stack?

**Comment by kgerheiser** [comment] 2021-07-27 13:54
It runs on Hera, Orion, and Jet. I have added you.

**Comment by edwardhartnett** [comment] 2021-07-27 13:55
Are we going to add my systems? Or shall we close this issue?

**Comment by climbfuji** [comment] 2021-07-27 19:18
We should try to get this going on Cheyenne after the downtime this week.

**Comment by kgerheiser** [comment] 2021-07-27 19:21
See instructions here: https://github.com/NOAA-EMC/hpc-stack/tree/develop/cron-ci

It's pretty simple to setup. You just fill out `setup-cron.sh` and set a few working directories. Then, set Cron to run that script at whatever interval.

**Comment by climbfuji** [comment] 2021-12-17 14:32
@mark-a-potts Since EPIC will be taking care of Cheyenne in the future, this might be of interest to you. Cheyenne doesn't have automated, cron-based testing of building hpc-stack yet.

**Comment by mark-a-potts** [comment] 2021-12-20 15:08
Thanks for the tip. I started testing this out this morning, but ran into an issue of szip missing while building stack_ufs_weather_ci.yaml. Obviously, I can enable the szip build in that yaml file, but shouldn't that be built by default anyway? Is this the yaml file I should be using or should I just stick with stack_noaa.yaml?

**Comment by climbfuji** [comment] 2021-12-20 15:14
I always thought that `szip` should be built.

**Comment by edwardhartnett** [comment] 2021-12-20 16:05
Is anyone using szip to produce netCDF data? I'm pretty sure we don't want to do that...

**Comment by climbfuji** [comment] 2021-12-20 16:21
> Thanks for the tip. I started testing this out this morning, but ran into an issue of szip missing while building stack_ufs_weather_ci.yaml. Obviously, I can enable the szip build in that yaml file, but shouldn't that be built by default anyway? Is this the yaml file I should be using or should I just stick with stack_noaa.yaml?

Building `szip` is turned off in the CI stack yaml file, but it's on in the NOAA yaml file. I checked that both have the szip option for hdf5 disabled:
```
hdf5:
  build: YES
  version: 1.10.6
  shared: NO
  enable_szip: NO
  enable_zlib: YES
```
In which package is the build failing?

**Comment by kgerheiser** [comment] 2021-12-20 16:25
PIO does a `module load szip` that should be a `try-load`, is that the error you got?

**Comment by mark-a-potts** [comment] 2021-12-20 17:07
Yes, that is where it is failing. PIO.

**Comment by aerorahul** [comment] 2023-04-29 14:21
This will not be worked on. Closing.

**Closed as not planned** 2023-04-29 14:21 UTC
Labels: enhancement
