### ISSUE TITLE
HPC stack build on Jet Failed 8/16

### ISSUE THREAD

**Issue by GeorgeVandenberghe-NOAA** [NOAA-EMC/hpc-stack#307] opened 2021-08-17 14:49 UTC
HPCSTACK build on Jet 8/17/2021  from the following script FAILED in bufrlib build

git clone https://github.com/NOAA-EMC/hpc-stack.git h0816
cd h0816

export P=/tmp/hpcstackF

rm -rf $P
./setup_modules.sh -p $P  -c config/config_jet.sh
./build_stack.sh -p  $P  -c ./config/config_jet.sh -y ./stack/stack_noaa.yaml

ld/test/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/hom                                                                                                             e/George.Vandenberghe/th4/hpcstack/h0816/pkg/bufr-bufr_v11.5.0/build/test/CMakeF                                                                                                             iles/test_OUT_6_8_DA.x.dir/depend.internal".
Scanning dependencies of target test_OUT_6_8_DA.x
make[2]: Leaving directory `/mnt/lfs4/HFIP/hfv3gfs/gwv/hpcstack/h0816/pkg/bufr-b                                                                                                             ufr_v11.5.0/build'
make  -f test/CMakeFiles/test_OUT_6_8_DA.x.dir/build.make test/CMakeFiles/test_O                                                                                                             UT_6_8_DA.x.dir/build
make[2]: Entering directory `/mnt/lfs4/HFIP/hfv3gfs/gwv/hpcstack/h0816/pkg/bufr-                                                                                                             bufr_v11.5.0/build'
[100%] Linking Fortran executable split_by_subset.x
cd /home/George.Vandenberghe/th4/hpcstack/h0816/pkg/bufr-bufr_v11.5.0/build/util                                                                                                             s && /misc/apps/cmake/3.20.1/bin/cmake -E cmake_link_script CMakeFiles/split_by_                                                                                                             subset.x.dir/link.txt --verbose=N
[100%] Building Fortran object test/CMakeFiles/test_OUT_6_8_DA.x.dir/test_OUT_6.                                                                                                             f.o
cd /home/George.Vandenberghe/th4/hpcstack/h0816/pkg/bufr-bufr_v11.5.0/build/test                                                                                                              && /apps/intel/parallel_studio_xe_2018.4.057/compilers_and_libraries_2018/linux                                                                                                             /bin/intel64/ifort -DDYNAMIC_ALLOCATION -DUNDERSCORE -I/home/George.Vandenberghe                                                                                                             /th4/hpcstack/h0816/pkg/bufr-bufr_v11.5.0/src -I/home/George.Vandenberghe/th4/hp                                                                                                             cstack/h0816/pkg/bufr-bufr_v11.5.0/build/src/include/bufr_8_DA -fPIC -w -g -trac                                                                                                             eback -O3 -fPIE -r8 -i8 -c /home/George.Vandenberghe/th4/hpcstack/h0816/pkg/bufr                                                                                                             -bufr_v11.5.0/test/test_OUT_6.f -o CMakeFiles/test_OUT_6_8_DA.x.dir/test_OUT_6.f                                                                                                             .o
make[2]: Leaving directory `/mnt/lfs4/HFIP/hfv3gfs/gwv/hpcstack/h0816/pkg/bufr-b                                                                                                             ufr_v11.5.0/build'
[100%] Built target gettab.x
[100%] Linking Fortran executable test_OUT_6_8_DA.x
cd /home/George.Vandenberghe/th4/hpcstack/h0816/pkg/bufr-bufr_v11.5.0/build/test                                                                                                              && /misc/apps/cmake/3.20.1/bin/cmake -E cmake_link_script CMakeFiles/test_OUT_6                                                                                                             _8_DA.x.dir/link.txt --verbose=N
make[2]: Leaving directory `/mnt/lfs4/HFIP/hfv3gfs/gwv/hpcstack/h0816/pkg/bufr-b                                                                                                             ufr_v11.5.0/build'
[100%] Built target split_by_subset.x
make[2]: Leaving directory `/mnt/lfs4/HFIP/hfv3gfs/gwv/hpcstack/h0816/pkg/bufr-b                                                                                                             ufr_v11.5.0/build'
[100%] Built target test_OUT_6_8_DA.x
curl: (28) Connection timed out after 30001 milliseconds
make[2]: *** [test/bufr.tar] Error 28
make[2]: Leaving directory `/mnt/lfs4/HFIP/hfv3gfs/gwv/hpcstack/h0816/pkg/bufr-b                                                                                                             ufr_v11.5.0/build'
make[1]: *** [test/CMakeFiles/get_bufr_test_data.dir/all] Error 2
make[1]: Leaving directory `/mnt/lfs4/HFIP/hfv3gfs/gwv/hpcstack/h0816/pkg/bufr-b                                                                                                             ufr_v11.5.0/build'
make: *** [all] Error 2

**Comment by aerorahul** [comment] 2021-08-17 14:54
@GeorgeVandenberghe-NOAA 
Does jet allow `wget` or `curl` from the WWW?
The error shows:
***curl: (28) Connection timed out after 30001 milliseconds make[2]: *** [test/bufr.tar] Error 28***

```
make[2]: Leaving directory /mnt/lfs4/HFIP/hfv3gfs/gwv/hpcstack/h0816/pkg/bufr-b ufr_v11.5.0/build' [100%] Built target test_OUT_6_8_DA.x curl: (28) Connection timed out after 30001 milliseconds make[2]: *** [test/bufr.tar] Error 28 make[2]: Leaving directory /mnt/lfs4/HFIP/hfv3gfs/gwv/hpcstack/h0816/pkg/bufr-b ufr_v11.5.0/build'
make[1]: *** [test/CMakeFiles/get_bufr_test_data.dir/all] Error 2
```

**Comment by aerorahul** [comment] 2021-08-17 15:21
@GeorgeVandenberghe-NOAA 
After the bufr library is built, the bufr build system tries to download the test data.
https://github.com/NOAA-EMC/NCEPLIBS-bufr/blob/9408871c8b7b9283f7442e58448874184bf2eb96/test/CMakeLists.txt#L49
That is where the failure is occurring on Jet.
May be this should be removed from `ALL` targets and be executed only when tests are run (which they are not in hpc-stack by default `MAKE_CHECK=NO`).
You will experience this error if you tried to build the bufr library outside of hpc-stack.

**Comment by GeorgeVandenberghe-NOAA** [comment] 2021-08-17 16:02
So if I don't have connectivity and want to just get the library built without testing since this NOAA platform doesn't support the testing capability,  how do I get rid of the test?

**Comment by GeorgeVandenberghe-NOAA** [comment] 2021-08-17 16:23
I am concerned we might have to build HPC_STACK as a guest on some other machine somewhere with different security requirements and lack of connectivity.  Finding an alternate way to get bufr.test into this package in the build is not trivial.  Being able to create a tarball on well connected machine A and untar it on machine B inside firewalls, without good connectivity and build with everything available in the tarball without external connections, would be helpful

**Comment by aerorahul** [comment] 2021-08-17 16:30
@GeorgeVandenberghe-NOAA 

hpc-stack does provide a mechanism where one can "download" the source code on a machine with connectivity, rsync/scp manually to firewalled machine, and then use it.  The option is called `DOWNLOAD_ONLY=YES|NO` in `config.sh`.
See the documentation of hpc-stack regarding the use of `DOWNLOAD_ONLY` [here](https://github.com/NOAA-EMC/hpc-stack/#using-the-download_only-option).

This issue is not with the source code, but with test data.
NCEPLIBS-bufr is pulling down test data regardless of whether it/user wants to run tests or not.
This is a change required in `NCEPLIBS-bufr`.

**Comment by GeorgeVandenberghe-NOAA** [comment] 2021-08-17 16:39
I've used that download only capability and it works great but it is defeated when there are additional downloads embedded within a build script downloaded from the repository and not activated until the build is executed.  Yeah.. that problem is in the repository, not HPC_STACK, agreed but it still is a real problem when we have to do a build on some foreign machine with poor connectivity and it's why I stuck with a tarball build rather than repository clones for a long time.  Tarball builds are, agreed,  obsolete but I would like to see a download option for all of our repository stuff and no additional downloads in the build.
Ironically I was doing this to check out the PIO build and this problem hasn't given me a chance to look at THAT problem (PIO builds fine on Jet login nodes by the way)

**Comment by aerorahul** [comment] 2021-08-17 16:45
If you want to solve the `PIO` problem, turn off everything in `stack.yaml` that `PIO` does not need.  
You are probably wasting your time beating around problems that have no relevance to the issue you are trying to solve.

To download just the source code for a package is one thing.  To download everything that the individual packages will download when they start to build is another and way more complicated to solve.  This will not be solved in hpc-stack.

I am going to close this issue, because this is not a bug in hpc-stack.
At best, this is a desired enhancement that will not be addressed anytime soon.

**Closed as completed by aerorahul** 2021-08-17 16:45 UTC
Labels: bug

**Comment by GeorgeVandenberghe-NOAA** [comment] 2021-08-17 16:50
Acknowledged.  THis is outside of HPC_STACK and needs to be addressed in the packages it builds.  I concur with the close.
