### ISSUE TITLE
install esmf810bs36 in hpc stack

### ISSUE THREAD

**Issue by junwang-noaa** [NOAA-EMC/hpc-stack#41] opened 2020-11-03 16:50 UTC
ESMF team has updated esmf to esmf810bs36, we need this library to be built in hpc stack in both regular and debug mode to test the new features in this esmf version. We need the lib on hera/orion/dell

**Comment by rsdunlapiv** [comment] 2020-11-03 16:56
ESMF snapshots come out fairly frequently, so we should have a process to request this.  Should we plan to create an issue whenever we need a new snapshot built?

**Comment by Hang-Lei-NOAA** [comment] 2020-11-03 19:31
I will added these to the testing versions of hpc-stack

**Comment by Hang-Lei-NOAA** [comment] 2020-11-04 20:12
They (both debug and normal of 810bs36) are added.

**Comment by edwardhartnett** [comment] 2020-11-19 15:56
This seems to be a duplicate of #77.

**Comment by kgerheiser** [comment] 2020-11-19 15:57
Yes, I missed this.

**Comment by edwardhartnett** [comment] 2020-11-19 16:05
OK, we will close this with #77.

**Comment by junwang-noaa** [comment] 2020-11-19 16:14
Ed, as Rocky asked, I am still not clear what is the  process to request
ESMF lib that is frequently changing under hpc stack?

**Comment by edwardhartnett** [comment] 2020-11-19 16:22
@junwang-noaa and @rsdunlapiv we are about to do a 1.1.0 release of hpc-stack which supports both of the ESMF versions you require.

I will open a separate issue about how we may best support multiple, and rapidly changing, ESMF releases.

For now, yes, please open an issue every time you need a new ESMF snapshot installed.

**Comment by edwardhartnett** [comment] 2020-11-20 18:13
I believe this may be closed now.

**Closed as completed by edwardhartnett** 2020-11-20 18:13 UTC
Labels: duplicate
