### ISSUE TITLE
Install FMS library 

### ISSUE THREAD

**Issue by junwang-noaa** [NOAA-EMC/hpc-stack#199] opened 2021-03-31 15:34 UTC
**Is your feature request related to a problem? Please describe.**
FMS is currently built in UFS. Since it does not change frequently, it would be more efficient to build it as a library and the UFS build system will link it at build time. 

**Describe the solution you'd like**
Now according to @aerorahul  FMS is in hpc-stack, please build the FMS library (both real4 and real8 libraries) at a test location on UFS supported platforms: dell, cray, hera, jet, orion, gaea, so that we can test it in the UFS.

**Comment by aerorahul** [comment] 2021-03-31 15:42
@junwang-noaa 
This is the current build option for FMS from `stack_noaa.yaml`

```
fms:
  build: YES
  version: 2020.04.03
  repo: noaa-gfdl
  cmake_opts: "-DGFS_PHYS=ON -D64BIT=ON -DOPENMP=ON"
```

It will build the `2020.04.03` tag in both single and double precision libraries with `OpenMP`.

**Comment by junwang-noaa** [comment] 2021-03-31 15:48
That is great, thanks. We can test it in UFS once it is available.

**Comment by climbfuji** [comment] 2021-04-05 16:21
Would this be a good opportunity to roll out a new version of hpc-stack (v1.2.0?) created from develop? We have to make so many manual adjustments to hpc-v1.1.0 in order to install it on new platforms / install new packages.

**Comment by junwang-noaa** [comment] 2021-04-06 00:33
@edwardhartnett Please see the Dom comments. Also do you have a time line when the FMS library will be installed? Thanks.

**Comment by edwardhartnett** [comment] 2021-04-06 12:45
@Hang-Lei-NOAA @EricSinsky-NOAA @aerorahul shall we do a v1.2.0 release? 

@Hang-Lei-NOAA can you add FMS and install it?

**Comment by Hang-Lei-NOAA** [comment] 2021-04-06 12:52
Yes, will do

**Comment by aerorahul** [comment] 2021-04-06 13:51
@edwardhartnett @kgerheiser 
Would it be possible to include the following in the 1.2.0 tag of hpc-stack (in addition to the above):
- NCEPLIBS-ncio (if a tag is imminent?  There was some updates to documentation going on.)
- NCEPLIBS-wrf_io (so it works with the GSI as well as UPP)
- NCEPLIBS-bufr (its been a while since a tag was created and released; 11.4.0. was the last and it doesn't have the later python updates and modifications to source code @jbathegit)
- NCEPLIBS-w3emc now contains NCEPLIBS-w3nco and users should be encouraged to remove dependence on w3nco from their codes so we don't carry duplicate copies.  This may not be trivial, but is worth a shot.

This should be discussed separately, but since the conversation has already begun, I bring it up here.

**Comment by edwardhartnett** [comment] 2021-04-06 13:55
I think that's a good idea for ncio, wrf_io, and w3emc. I will defer to @jbathegit on bufr, but more frequent releases are to be encouraged, so I think that should be done as well.

**Comment by jbathegit** [comment] 2021-04-06 14:13
I'm just working on documentation updates at the moment.  I was hoping to get all of this done to include in the next release, but it's been a bit of a grind, and I realize there's new functionality (such as Python ;-) that folks would like to have sooner rather than later.  So how about this - can you give me another week or so to just finish up a few more documentation updates (including to the User Guide), and then I'll be fine with going ahead with a new release and will just keep plugging away at the rest of the documentation at a later date?

One question though - I thought the next upcoming release was going to be 11.4.0(?)  If not then when was 11.4.0 released, and by whom?  Looking at https://github.com/NOAA-EMC/NCEPLIBS-bufr/releases, my understanding had always been that 11.3.2 was the "Latest release" and 11.4.0 was a "Draft" (i.e. the next upcoming) release.  In other words, I didn't realize there was an 11.4.0 tag floating around out there, and if so then I guess this next one will need to be 11.5.0(?)  If that's the case, are there any release notes available for 11.4.0, aside from the few items mentioned at the above URL?

Just want to make sure we're all on the same page here! ;-)

**Comment by aerorahul** [comment] 2021-04-06 14:22
@jbathegit 
My bad.  I "treated" the 11.4.0 as a release rather than a `draft` release as it is.  You are welcome to use 11.4.0, but I think it would be better to skip 11.4.0 and go to 11.5.0 and not let it be draft for long.  I have no strong preference and leave it to you to decide how you wish to manage releases.

I think it is safe to say, we won't be releasing a new hpc-stack tag in this week, so you definitely have a week (at least) to get your side of things in place.

**Comment by arunchawla-NOAA** [comment] 2021-04-07 13:20
@edwardhartnett can we get a test stack installation on at least one of the platforms with FMS library available while we are waiting for the official v1.2.0 tag? This will allow the ufs-weather-model code mangers to update and test the build system by switching off FMS build and getting a PR ready for when v 1.2.0 is available

**Comment by Hang-Lei-NOAA** [comment] 2021-04-07 14:29
Yes, I will install it on Hera and WCOSS-dell first.

**Comment by Hang-Lei-NOAA** [comment] 2021-04-07 23:47
According to Arun's order, this has been added to current hpc-stack installation of v1.1.0 on hera and Mars.

**Comment by kgerheiser** [comment] 2021-04-08 18:23
Done on Orion and Jet

**Comment by arunchawla-NOAA** [comment] 2021-04-08 18:36
Thanks @kgerheiser and @Hang-Lei-NOAA 

I hate to ask more in the same request, but we also need to upgrade cmake to 3.20.0. It has been released and we are going to ask system admins to do that, but in the mean time can we add that as part of hpc-stack? If you can do on Hera then the @DusanJovic-NOAA can test the ufs-weather-model build for FMS library

**Comment by Hang-Lei-NOAA** [comment] 2021-04-08 21:37
Hi, Arun, I have get cmake v3.20.0 installed on hera through hpc-stack
v1.1.0.

**Comment by DusanJovic-NOAA** [comment] 2021-04-13 13:10
Please add AVX2 flag to the FMS compile flags (`-march=core-avx2` for Intel) . It was found during the UFS regression testing that the model is running noticeably slower when compiled with external FMS library than with the FMS built as a submodule.

**Comment by Hang-Lei-NOAA** [comment] 2021-04-13 13:24
Will do.

**Comment by kgerheiser** [comment] 2021-04-13 13:27
@Hang-Lei-NOAA the way to do this would be `export STACK_fms_CFLAGS="-march=core-avx2"`

**Comment by Hang-Lei-NOAA** [comment] 2021-04-13 13:42
@Kyle Gerheiser - NOAA Affiliate ***@***.***> I've added it in
the build script

**Comment by kgerheiser** [comment] 2021-04-13 13:44
Oops, those are CFLAGS. Probably want Fortran (`STACK_fms_FFLAGS`) also (or instead).

**Comment by Hang-Lei-NOAA** [comment] 2021-04-13 13:48
Thanks, Kyle, I added it as in the libs/build_fms.sh
export CFLAGS="${STACK_CFLAGS:-} ${STACK_fms_CFLAGS:-} -fPIC -w
-march=core-avx2"
export FFLAGS="${STACK_FFLAGS:-} ${STACK_fms_FFLAGS:-} -fPIC -w
-march=core-avx2"
export FCFLAGS="${FFLAGS}"

**Comment by aerorahul** [comment] 2021-04-13 13:57
@Hang-Lei-NOAA 
These are machine specific flags; please don't add them in the `libs/build_fms.sh` script.
Their appropriate location is in `config/config_<platform>.sh` for the platform where those flags are valid.
Please add them according to the instructions @kgerheiser provided.
```
export STACK_fms_CFLAGS="-march=core-avx2"
export STACK_fms_FFLAGS="-march=core-avx2"
```
Please create a branch, create an issue and open a PR, so that this does not need to be re-done during the next installation of the stack.

**Comment by aerorahul** [comment] 2021-04-13 13:58
@DusanJovic-NOAA @climbfuji 
Which platforms do these flags need to be added; `orion`, `hera`, `wcoss_dell_p3`, `cheyenne`, `gaea?`

**Comment by Hang-Lei-NOAA** [comment] 2021-04-13 14:03
I've installed it on both wcoss-dell and hera and changed the script back.
If add them in other places, we need to add

export STACK_fms_CFLAGS="-fPIC -w -march=core-avx2"
export STACK_fms_FFLAGS="-fPIC -w -march=core-avx2"

otherwise the -fPIC -w will be flashed

**Comment by climbfuji** [comment] 2021-04-13 14:10
> @DusanJovic-NOAA @climbfuji
> Which platforms do these flags need to be added; `orion`, `hera`, `wcoss_dell_p3`, `cheyenne`, `gaea?`

For now (testing), hera and wcoss_dell_p3 should be enough, once we are confident that all the flags etc are as they should be, it needs to go to `orion`, `hera`, `wcoss_dell_p3`, `wcoss_cray` `cheyenne`, `gaea`, `jet`. On `hera` and `cheyenne` for both Intel and GNU, all other platforms just Intel.

**Comment by kgerheiser** [comment] 2021-04-13 14:14
We could just add it to the build? AVX2 is a pretty tame flag. Most CPUs since 2014 support those instructions. Or add it to all of the HPC configs.

**Comment by Hang-Lei-NOAA** [comment] 2021-04-13 14:20
We can do it anyway. It is a patch.
I just add it with GNU on hera too.

**Comment by climbfuji** [comment] 2021-04-13 14:23
Most but not all - it won't work on all jet partitions, for example.

**Comment by junwang-noaa** [comment] 2021-04-21 12:19
@kgerheiser @Hang-Lei-NOAA May I ask the status of installing fms with AVX2 on the UFS supported platforms?

**Comment by Hang-Lei-NOAA** [comment] 2021-04-21 12:25
Yes, it is done two weeks ago

**Comment by junwang-noaa** [comment] 2021-04-21 12:36
@Hang-Lei-NOAA Just want to confirm, so fms library is available on dell, cray, hera, jet, orion and gaea? Thanks

**Comment by kgerheiser** [comment] 2021-04-21 13:06
On Jet I didn't add the architecture flag because I don't think it's supported on all Jet partitions (correct me if I'm wrong).

**Comment by Hang-Lei-NOAA** [comment] 2021-04-21 13:08
Please check it on each platform one by one, and let us know if there is
any issue, since different machines are operated by different people.

**Comment by junwang-noaa** [comment] 2021-04-21 13:18
Thanks, Kyle and Hang. We will let you know how the testing is going.

**Comment by climbfuji** [comment] 2021-04-21 15:09
@kgerheiser Good call to not just add the AVX2 flags on jet. You could add the same flags we use for jet for the ufs-weather-model, or just leave it as-is:
```
-axSSE4.2,CORE-AVX2
```
See https://github.com/ufs-community/ufs-weather-model/blob/develop/cmake/Intel.cmake for the option `SIMDMULTIARCH`. We can add that to the jet hpc stack config for fms, if we want to.

**Comment by climbfuji** [comment] 2021-04-21 15:10
@junwang-noaa @Hang-Lei-NOAA @kgerheiser Do I need to install FMS (which version/options?) on gaea and cheyenne?

**Comment by junwang-noaa** [comment] 2021-04-21 15:13
Yes, please. We need to use FMS library in ufs-weather-model supported
platforms. Thanks

**Comment by climbfuji** [comment] 2021-04-21 15:17
> Yes, please. We need to use FMS library in ufs-weather-model supported platforms. Thanks
> […](#)

Thanks, if someone can tell me which version / what the config in hpc-stack looks like, that would be great.

**Comment by kgerheiser** [comment] 2021-04-21 15:20
The stack file doesn't need to change, but the config file needs the AVX flags.

```
export STACK_fms_CFLAGS="-march=core-avx2
export STACK_fms_FFLAGS="-march=core-avx2
```

**Comment by climbfuji** [comment] 2021-04-21 15:21
> The stack file doesn't need to change, but the config file needs the AVX flags.
> 
> ```
> export STACK_fms_CFLAGS="-march=core-avx2
> export STACK_fms_FFLAGS="-march=core-avx2
> ```

Thanks, will do as instructed.

**Comment by climbfuji** [comment] 2021-04-21 16:40
FMS module `noaa-gfdl-2020.04.03.lua` is now on Cheyenne for gnu9 (default), gnu10, intel19 (default) and on gaea for intel18 (default).

**Comment by junwang-noaa** [comment] 2021-04-29 02:37
@Hang-Lei-NOAA so we will also need cmake 3.18+ installed on the supported platforms in order to use fms library in the model, may I ask if you installed it? Thanks

**Comment by Hang-Lei-NOAA** [comment] 2021-04-29 12:11
Will get cmake3.20 done today according to this and other requests

**Comment by climbfuji** [comment] 2021-04-29 13:52
Note: FMS was installed and tested successfully on Cheyenne with Intel and GNU, and on Gaea with Intel.

- For Cheyenne/GNU, I had to add the FMS patch that was in ufs-weather-model to hpc-stack, this has been merged into develop. No need to install cmake, because cmake 3.18.4 is available as module and sufficient for FMS
- For Gaea, I had to install cmake, I did that manually outside of hpc-stack, created a module for it and sent @DusanJovic-NOAA the necessary updates to the gaea modulefiles (already part of his PR).

**Comment by kgerheiser** [comment] 2021-04-29 14:03
Thanks Dom

**Comment by edwardhartnett** [comment] 2021-05-06 13:33
Which repo is using FMS? fv3atm?

Is the CMake build in that repo testing for the presence and correct version of FMS? It needs to.

**Comment by arunchawla-NOAA** [comment] 2021-05-06 13:46
UFS-weather-model build system

**Comment by edwardhartnett** [comment] 2021-05-06 13:57
But the UFS-weather-model just assembles a bunch of repos. Which of those repos actually use FMS?

**Comment by junwang-noaa** [comment] 2021-05-06 14:08
fv3atm and mom6.

**Comment by edwardhartnett** [comment] 2021-05-06 15:08
Thanks I added issues to fv3atm and mom6.

I note mom6 is still using the mkmf build system that has plagued many GFDL builds. I offered to convert it to autotools, as I did for the FMS.

**Comment by aerorahul** [comment] 2021-07-08 15:34
FMS is being built and installed via hpc-stack.  This issue is out of date or irrelevant now.
Closing.
Reopen if it is still relevant.

**Closed as completed by aerorahul** 2021-07-08 15:34 UTC
