### ISSUE TITLE
Version 1.1.0 Installation and test status

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/hpc-stack#111] opened 2020-11-24 20:08 UTC
This issue is to track the test and installation status of hpc-stack on NOAA systems.

**Note.** The following table applies to the second pre-release tag 1.1.0, created 12/02/2020. The comments below, up to https://github.com/NOAA-EMC/hpc-stack/issues/111#issuecomment-738048057, relate to the first pre-release tag.

Platform | Installation Status | Tested with UFS Regression tests
-------- | ------------------ |--------
Orion     |      Installed (`/apps/contrib/NCEP/libs/hpc-stack/modulefiles/stack`)     | Pass with Intel
Hera      |     Installed   (`/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/modulefiles/stack`)      | Pass with Intel and GNU
Jet         | Installed (`lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/libs/modulefiles/stack`)             | Pass with Intel
Dell        | Installed (`/usrx/local/nceplibs/dev/hpc-stack/libs/hpc-stack/modulefiles/stack`)             | Pass with Intel
Cray      | NCEPLIBS v1.3.0 installed (`/usrx/local/nceplibs/NCEPLIBS/cmake/install/NCEPLIBS-v1.3.0/modules`)           | Pass with Intel
Gaea     |  Installed (`/lustre/f2/pdata/esrl/gsd/ufs/hpc-stack-v1.1.0`)            | Pass with Intel
Cheyenne | Installed (`/glade/p/ral/jntp/GMTB/tools/hpc-stack-v1.1.0`)         | Pass with Intel and GNU
macOS |     N/A                      |  Tested on macOS Mojave with LLVM clang 9.0.0 + GNU gfortran 9.2.0 + pre-installed mpich-3.3.1, using a canned test case and a recent hash (bfce1df1c03c3aef87c177cd0b04579d0ce5f430) of the ufs-weather-model

**Comment by climbfuji** [comment] 2020-11-24 20:12
Additional systems that have been tested:

- macOS Catalina with gcc-9.2.0/gfortran-9.2.0 and pre-installed mpich-3.3.1: installed, not yet tested

Update: ufs-weather-model crashes immediately when ESMF is starting up. I think this has to do with the optimization level. We should really mirror exactly what is used in NCEPLIBS-external, these flags have been tested backward and forward and are also approved by the ESMF team: lines 300-330 here https://github.com/NOAA-EMC/NCEPLIBS-external/blob/bbc872c0c4a2c18069562080d6f3419a4eabe7c9/CMakeLists.txt#L300

**Comment by climbfuji** [comment] 2020-11-24 21:59
> Additional systems that have been tested:
> 
> * macOS Catalina with gcc-9.2.0/gfortran-9.2.0 and pre-installed mpich-3.3.1: installed, not yet tested
> 
> Update: ufs-weather-model crashes immediately when ESMF is starting up. I think this has to do with the optimization level. We should really mirror exactly what is used in NCEPLIBS-external, these flags have been tested backward and forward and are also approved by the ESMF team: lines 300-330 here https://github.com/NOAA-EMC/NCEPLIBS-external/blob/bbc872c0c4a2c18069562080d6f3419a4eabe7c9/CMakeLists.txt#L300

This failure alone means that we need to open up the release, fix `libs/build_esmf.sh` and retag.

**Comment by climbfuji** [comment] 2020-11-24 22:55
> > Additional systems that have been tested:
> > 
> > * macOS Catalina with gcc-9.2.0/gfortran-9.2.0 and pre-installed mpich-3.3.1: installed, not yet tested
> > 
> > Update: ufs-weather-model crashes immediately when ESMF is starting up. I think this has to do with the optimization level. We should really mirror exactly what is used in NCEPLIBS-external, these flags have been tested backward and forward and are also approved by the ESMF team: lines 300-330 here https://github.com/NOAA-EMC/NCEPLIBS-external/blob/bbc872c0c4a2c18069562080d6f3419a4eabe7c9/CMakeLists.txt#L300
> 
> This failure alone means that we need to open up the release, fix `libs/build_esmf.sh` and retag.

Additional issues I have come across so far:
- with LLVM clang, cannot build netcdf-cxx, easiest way is to comment out everything related to it in `libs/build_netcdf.sh` (there is no way unfortunately to say I want netcdf-c and netcdf-fortran, but not netcdf-cxx; the latter isn't used by the ufs-weather-model)
- with LLVM clang, json-schema-validator fails with errror
```
CMake Error at CMakeLists.txt:24 (target_compile_features):
  target_compile_features no known features for CXX compiler

  "Clang"

  version 9.0.0.
```
- when building only ESMF (for example to overwrite the existing one with a version that has the correct flags) on macOS where modules aren't used, I need to manually set HDF5_ROOT and NETCDF_ROOT to the hpc-stack install prefix for build_esmf.sh to work
- more of a question: with a flat install for macOS, can't install ESMF bs27 and bs36 at the same time?

**Comment by kgerheiser** [comment] 2020-11-24 23:44
Ok, we can replicate the flags for ESMF. I agree that it's probably the optimization level.
In NCEPLIBS-external, for Apple, there's this: `set(ESMF_OPTLEVEL "0")` and `set(ESMF_BOPT "O")`

Other than that, the flags looks the same.


For `NetCDF-cxx`, we could add an option to disable building it?

I was able to build `json-schema-validator` in hpc-stack and standalone using Clang.

For a flat install you can't have two of the same library; the latter one will overwrite the former.

**Comment by kgerheiser** [comment] 2020-11-24 23:50
Oh, LLVM Clang. I didn't try that.

Update:

I installed clang10 (LLVM Clang) through MacPorts and was also able to build it.

**Comment by climbfuji** [comment] 2020-11-24 23:59
I built ESMF in debug mode, which should use no optimization. It's still crashing right away, so that alone isn't the issue. Is there a reason why we are building a dynamic ESMF library? The static library should do, or? I don't think this makes a difference for this particular problem, but I noted this difference to NCEPLIBS-external (which does only the static build). We also need to look into the other ESMF build flags.

For LLVM clang, the mechanism is to install it via homebrew and then set `CC=full/path/to/bin/clang` - this means that build systems don't recognize the compiler as `gcc`, but as `clang`. The advantage of LLVM clang is that it can do OpenMP, i.e. one can build wgrib2 and other libraries with OpenMP support. It's also the standard and supported way to use clang+gfortran for the UFS public releases (MRW 1.0, MRW 1.1, SRW 1.0) - none of these uses native clang.

**Comment by kgerheiser** [comment] 2020-11-25 00:11
Through some research perhaps setting this CMake policy for `json-schema-validator` will fix the problem:

`-DCMAKE_POLICY_DEFAULT_CMP0025=NEW`

**Comment by climbfuji** [comment] 2020-11-25 02:57
> Through some research perhaps setting this CMake policy for `json-schema-validator` will fix the problem:
> 
> `-DCMAKE_POLICY_DEFAULT_CMP0025=NEW`

Thanks, Kyle. Will try that tomorrow!

**Comment by Hang-Lei-NOAA** [comment] 2020-11-25 14:05
The hpc-stack/v1.1.0 has been installed on hera:
module use /scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/modulefiles/stack

The hpc-stack/v1.1.0 has been installed on wcoss dell:
module use /usrx/local/nceplibs/dev/hpc-stack/libs/hpc-stack

**Comment by kgerheiser** [comment] 2020-11-25 14:34
Kind of a tangent question @climbfuji, but how do you run the weather model on Mac using this hpc-stack? I built the model fine, and tried to run the `simple-test-case`, but that fails because I think it's for the public release and some things don't match what's currently in the weather model's develop branch (namelist fails). Is that right?

Is there some pre-packaged run I can use?

**Comment by climbfuji** [comment] 2020-11-25 14:46
> Kind of a tangent question @climbfuji, but how do you run the weather model on Mac using this hpc-stack? I built the model fine, and tried to run the `simple-test-case`, but that fails because I think it's for the public release and some things don't match what's currently in the weather model's develop branch (namelist fails). Is that right?
> 
> Is there some pre-packaged run I can use?

This is what I do, and it has been working fine for the last two years or so:
- check out the develop branch of the ufs-weather-model and build using `compile.sh`
- have a canned test case ready - you can get this once every now and then from one of the `rt.sh` runs that you do on one  of the tier-1 platforms, just need to adjust the number of tasks etc
- in my case, I have a little `run_macosx.sh` script in that directory, in which I only need to change one line (location of the source code), the script then links in the executable from that source directory and runs the model with six MPI tasks (one per tile for global C96 runs)

I can copy one of my canned test cases to a NOAA machine for you to download.

**Comment by kgerheiser** [comment] 2020-11-25 14:47
Yes, please.

**Comment by aerorahul** [comment] 2020-11-25 14:48
@climbfuji Please do share!!!
I started creating one of my own, but I need to make it general for the different cases and machine independent [here](https://github.com/aerorahul/ufs-tools/tree/run-ufs-standalone)

**Comment by climbfuji** [comment] 2020-11-25 15:01
> @climbfuji Please do share!!!
> I started creating one of my own, but I need to make it general for the different cases and machine independent [here](https://github.com/aerorahul/ufs-tools/tree/run-ufs-standalone)

Absolutely. I have several for different physics configurations, with restart runs etc. Also a regional one if I am not mistaken. Just want to make sure that each of them works with the latest version of the code before I share them.

**Comment by climbfuji** [comment] 2020-11-25 18:02
Just an update on the model crashes. I implemented the correct flags in `build_esmf.sh` - still no luck, still crashes.

I then went back and updated `NCEPLIBS-external` and `NCEPLIBS` to build ESMF bs27 instead of bs21, and upp instead of nceppost (everything else stayed as it was before when the model compiled and ran, I can reproduce that) - also crashes.

Three possibly culprits: (1) ESMF bs21->bs27 (2) nceppost->UPP (3) ufs-weather-model updates

I am going to look into all of these and let you know what I find.

**Update 1**: If I build the model with my previous stack without UPP, i.e. making two changes at the same time (bs27->bs21 and turning off inline post = upp), the model runs fine.

**Update 2**: If I build the model with my current stack without UPP, i.e. only changing ESMF from bs27 to bs21, the model immediately segfaults.

This is a strong hint that ESMF 8.1.0bs27 is the culprit. I will try hpc-stack with bs21 next (after lunch), if that works I will contact ESMF support.

**Update 3** and last update before Monday Nov 30: downgrading ESMF 8.1.0 to bs21 solves the problem. I will create a PR with updates for hpc-stack on Nov 30.

**Comment by kgerheiser** [comment] 2020-11-25 18:37
I was able to reproduce the LLVM Clang NetCDF C++ error and added an option to disable building it.

But still couldn't reproduce the json_schema_validator bug even with LLVM Clang.

**Comment by kgerheiser** [comment] 2020-11-27 23:57
Regression tests pass on Hera with Intel, fail with GNU

`module use /scratch2/NCEPDEV/nwprod/hpc-stack/test/modulefiles/stack`

They fail on Jet. I think it might be something wrong with the tests, or the default account rather than the libraries themselves.

`module use lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/libs/modulefiles/stack`

**Comment by kgerheiser** [comment] 2020-11-28 00:26
NetCDF doesn't load on WCOSS Dell for some strange reason:

```
Lmod has detected the following error:  Cannot load module "netcdf/4.7.4" without these module(s) loaded:
   hdf5

Executing this command requires loading "hdf5" which failed while processing the following module(s):

    Module fullname  Module Filename
    ---------------  ---------------
    netcdf/4.7.4     /gpfs/dell2/usrx/local/nceplibs/dev/hpc-stack/libs/hpc-stack/modulefiles/mpi/ips/18.0.1.163/impi/18.0.1/netcdf/4.7.4.lua
While processing the following module(s):
    Module fullname  Module Filename
    ---------------  ---------------
    netcdf/4.7.4     /gpfs/dell2/usrx/local/nceplibs/dev/hpc-stack/libs/hpc-stack/modulefiles/mpi/ips/18.0.1.163/impi/18.0.1/netcdf/4.7.4.lua
```

But I have HDF5 loaded when I do `module list`

`10) hdf5/1.10.6`

**Comment by kgerheiser** [comment] 2020-11-28 01:06
@Hang-Lei-NOAA how did you install hpc-stack on WCOSS Dell? After running into the aforementioned issue I tried installing it in my space and I can't even get hpc-stack to build. 

```
[Kyle.Gerheiser@v71a1 hpc-stack]$ ./build_stack.sh -p /gpfs/dell2/emc/modeling/noscrub/Kyle.Gerheiser/install -c config/config_custom.sh -y config/stack_noaa.yaml -m
Compiler: ips/18.0.1.163
MPI: impi/18.0.1
Lmod has detected the following error:  These module(s) exist but cannot be loaded as requested: "hpc"
   Try: "module spider hpc" to see how to load the module(s).
```

Any ideas?

**Comment by Hang-Lei-NOAA** [comment] 2020-11-28 01:09
This is because of dell LMOD system requires an exact match of module with
version number.
E.g. if you try to do
module load hdf5
It will not be permitted. In this Lmod, hdf5 is different from hdf5/1.10.6
You have to do
module load hdf5/1.10.6
Therefore, we have to modify
the /gpfs/dell2/usrx/local/nceplibs/dev/hpc-stack/libs/hpc-stack/modulefiles/mpi/ips/
18.0.1.163/impi/18.0.1/netcdf/4.7.4.lua
to replace the
load("hdf5")      ->   load("hdf5 /1.10.6 ")
prereq("hdf5")   ->    prereq("hdf5 /1.10.6 ")

**Comment by aerorahul** [comment] 2020-11-28 01:13
@kgerheiser See the known works around section of the readme. Then refer to config_wcoss_dell.sh

**Comment by Hang-Lei-NOAA** [comment] 2020-11-28 01:20
Thanks Rahul
It is added there.
@Kyle Gerheiser - NOAA Affiliate <kyle.gerheiser@noaa.gov>  Please try it
again.

**Comment by kgerheiser** [comment] 2020-11-30 15:16
@Hang-Lei-NOAA the NetCDF module still doesn't work. Could you update it?

It's still 

```
load("hdf5")
prereq("hdf5")
```

```
/gpfs/dell2/usrx/local/nceplibs/dev/hpc-stack/libs/hpc-stack/modulefiles/mpi/ips/18.0.1.163/impi/18.0.1/netcdf/4.7.4.lua
```

**Comment by Hang-Lei-NOAA** [comment] 2020-11-30 15:22
I double checked. I have uncommented the lines that Rahul suggested.
This time I further modified netcdf. Please try it again.

**Comment by climbfuji** [comment] 2020-11-30 15:49
For your information, I raised an issue about the ufs-weather-model crashes on macOS when updating from ESMF 8.1.0 bs 21 to 27 (or 38): https://github.com/ufs-community/ufs-weather-model/issues/303

For now, we can work around this problem by using bs21 in `stack_mac.yaml`, but once the fv3atm updates for bs38 are merged (https://github.com/NOAA-EMC/fv3atm/pull/180), we need to have a solution.

**Comment by kgerheiser** [comment] 2020-11-30 23:58
Regression tests pass on WCOSS-Dell

**Comment by climbfuji** [comment] 2020-12-03 03:12
@kgerheiser do we want to start with a clean plate, remove all the comments in this issue and update the table for the new hpc-stack v1.1.0 tag?

**Comment by edwardhartnett** [comment] 2020-12-03 13:29
Certainly we will not remove the comments in this issue, as they contain valuable history.

Has the tag been moved to the proper release version now?

**Comment by kgerheiser** [comment] 2020-12-03 14:09
Yes, it has

**Comment by climbfuji** [comment] 2020-12-03 14:53
> Certainly we will not remove the comments in this issue, as they contain valuable history.
> 
> Has the tag been moved to the proper release version now?

Should we add at least a note like _outdated_ or _was relevant to first pre-release_ or something like that to the comments that are no longer relevant? If we start populating the table in the description (i.e. at the top of the issue), nobody will remember that the table is newer than the comments below. Or add a comment to the table to provide clarification?

**Comment by edwardhartnett** [comment] 2020-12-03 14:57
Update or repeat the table, it's OK either way.

**Comment by kgerheiser** [comment] 2020-12-03 16:53
WCOSS Cray works

**Comment by climbfuji** [comment] 2020-12-03 16:54
> WCOSS Cray works

I added a note to the table and started updating it, would you mind doing the same, please?

**Comment by kgerheiser** [comment] 2020-12-03 16:57
I updated the table, is there something else you want me to do?

**Comment by climbfuji** [comment] 2020-12-03 16:58
> I updated the table, is there something else you want me to do?

No, thanks, that's great. Just curious, are you going to do some macOS tests as well?

**Comment by kgerheiser** [comment] 2020-12-03 17:06
I can. 

I think I figured out how to get a test case by passing `-k` to the regression test and then `scp` the data and editing `model_configure`. 

I took `fv3_ccpp_control_prod`. Is that a good one to try?

**Comment by climbfuji** [comment] 2020-12-03 17:11
> I can.
> 
> I think I figured out how to get a test case by passing `-k` to the regression test and then `scp` the data and editing `model_configure`.
> 
> I took `fv3_ccpp_control_prod`. Is that a good one to try?

Any will do, the most relevant is probably `fv3_ccpp_gfs_v16beta`. I wanted to upload a canned test case to S3, hoping I get to this at some point!

**Comment by edwardhartnett** [comment] 2020-12-04 14:49
Has hpc-stack-1.1.0 be installed on gaia yet? @climbfuji you are listed as doing that install - it is the last one we are waiting for before calling 1.1.0 released...

**Comment by climbfuji** [comment] 2020-12-04 14:51
> Has hpc-stack-1.1.0 be installed on gaia yet? @climbfuji you are listed as doing that install - it is the last one we are waiting for before calling 1.1.0 released...

Will do this morning. Same for Cheyenne (it's also in the list).

**Comment by kgerheiser** [comment] 2020-12-04 15:27
I re-ran the GNU regression tests on Hera and they passed

**Comment by climbfuji** [comment] 2020-12-04 17:03
Cheyenne and Gaea are cruising along with their installs ... takes a while. Will do the debug modulefiles as well.

**Comment by climbfuji** [comment] 2020-12-04 19:17
Installed on gaea, regression tests passed. Cheyenne still running.

**Comment by climbfuji** [comment] 2020-12-04 20:47
Installed on cheyenne for GNU and Intel. GNU tests passed, for Intel several tests failed - seems to be an issue with the system, not the libraries (compile job hang and timed out). Rerunning Intel now.

**Comment by climbfuji** [comment] 2020-12-04 22:31
Finally, the regression tests passed on Cheyenne with Intel, too.

**Comment by climbfuji** [comment] 2020-12-04 22:31
I'd say the release is good to go.

**Closed as completed** 2020-12-05 00:25 UTC
Labels: Install
